telegram:
  api-url: "https://api.telegram.org/"
  webhook-path: "webhook-url"
  bot-name: "name"
  bot-token: "token"
  host-url: http://localhost:7979/server/user/
spring:
  #    host: "<...>.compute-1.amazonaws.com"
  port: "1234"
  #    password:
  ssl: true
server:
  port: "1234"
